[package]
name = "tlvm"
version = "0.1.0"
edition = "2021"
description = "Tolvemi (tlvm): exec layer of LPTL v1"
license = "MIT OR Apache-2.0"

[dependencies]
num-bigint = "0.4"
num-integer = "0.1"
num-traits = "0.2"
tlvm-verified = { path = "../../verus" }

[[bin]]
name = "tlvm"
path = "src/main.rs"
